### PR TITLE
Updates testing for Fire method && Working on Fire Coordinate method.

### PR DESCRIPTION
**Pull request by priyapower**
Updates to Fire:
- No changes in Class
- Updates tests with comment lines for quick understanding
- This also checks that when one cell is fired_upon, other cells that have been fired_on before still retain their data and render correctly!

Work on Fire Coordinate:
- began conditional for @user
- current broken code (and pry location) is at validation step
- Also had inspiration to use the gets chomp (or similar) to auto cut characters down to first two user input

Future Work on Fire Coordinate:
-If I return to this work before you get a chance to see, as I update and push I will add detailed comments of work completed.

**Would love**
-If you could please review my code and point out refactor
-Suggestions for fire_coordinate behavior
-Work on results method

### CODE REVIEW

**Comment by priyapower** [comment]
-figured out fix for cutting off characters from gets
-Working on a drastic over haul of my original thought process for fire_coordinate.
-Attempting work through various helper methods as I follow the logic.
-Current work is on automation method for coordinates, then will work on user logic validaton.

**Comment by priyapower** [comment]
Man, me and this one fire coordinates method. I keep getting stuck with looping issues as I try to guard against user error. I am working them through using pry and helper methods, so I am trying to accomplish this methodologically. I would **love** to talk this through and maybe hear some ideas about where to go. Basically, I'm pooped from looking at code. I got it to a decent point, but if you currently run the file and user input "B2", you get the misfire message (which is awesome), but when you try to input a new coord, you get stuck in gets.chomp and it kills my terminal... So, I needed a break. See you in the morning!!

**Comment by priyapower** [comment]
THANK YOU! We peer talked this through when I got stuck with a scope logic. It should be passing code now! All we need to do is test :)

**Comment by priyapower** [comment]
FINALLY! Working code AND all methods tested!!!! Yay :) This is ready for review and possible merge. Let me know if I can update anything.

**Comment by Arique1104** [comment]
Hey Priya,

I would love to figure out how to mock/stub your game tests where random coordinates are being expected.  Other than that, I do believe there is a board test that is failing that I would like to decide together if we should delete or what we should test so that we can prove that it works.  Other than those two growth-opportunities for us, this looks phenomenal per usual!

**Comment by priyapower** [comment]
Saw your message about the board failure. Forgot to write it up. I saw it, it's not a "true" failure, it was an issue with the string expected (needs a space in a spot that's missing). BUT - I would LOVE to practice mocks and stubs after our lesson today!

**Pull request merged**
